# Generated by Django 6.0.2 on 2026-02-11 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_playermatchstats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playermatchstats',
            old_name='assits',
            new_name='assists',
        ),
    ]
