# Generated by Django 6.0.2 on 2026-02-11 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_assits_playermatchstats_assists'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectiveEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective_type', models.CharField(choices=[('dragon', 'Dragon'), ('baron', 'Baron'), ('tower', 'Tower'), ('grubs', 'Void Grubs'), ('herald', 'Herald')], max_length=20)),
                ('minute', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.team')),
            ],
        ),
    ]
