# Generated by Django 6.0.2 on 2026-02-11 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_objectiveevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectiveevent',
            name='timestamp_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Vod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.match')),
            ],
        ),
    ]
