# Generated by Django 6.0.2 on 2026-02-11 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_objectiveevent_timestamp_seconds_vod'),
    ]

    operations = [
        migrations.AddField(
            model_name='vod',
            name='game_start_offset_seconds',
            field=models.IntegerField(default=0),
        ),
    ]
