# Generated by Django 6.0.2 on 2026-02-12 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_vod_game_start_offset_seconds'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMatchSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(max_length=10)),
                ('bans_1', models.CharField(blank=True, default='', max_length=50)),
                ('bans_2', models.CharField(blank=True, default='', max_length=50)),
                ('bans_3', models.CharField(blank=True, default='', max_length=50)),
                ('bans_4', models.CharField(blank=True, default='', max_length=50)),
                ('bans_5', models.CharField(blank=True, default='', max_length=50)),
                ('gold_k', models.FloatField(blank=True, null=True)),
                ('team_kills', models.IntegerField(blank=True, null=True)),
                ('towers', models.IntegerField(blank=True, null=True)),
                ('objectives_shorthand', models.CharField(blank=True, default='', max_length=200)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.team')),
            ],
        ),
    ]
