# Generated by Django 6.0.2 on 2026-02-12 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_teammatchsummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='duration_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='playermatchstats',
            name='cs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playermatchstats',
            name='gold',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
